# Generated by Django 3.0.9 on 2020-08-21 18:48

from django.db import migrations, models
import tenant_schemas.postgresql_backend.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_url', models.CharField(max_length=128, unique=True)),
                ('schema_name', models.CharField(max_length=63, unique=True, validators=[tenant_schemas.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=250, verbose_name='company name')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('on_trial', models.BooleanField()),
                ('paid_until', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
